"""
MongoDB Schema Documentation for Flask Inventory Management System

This application uses MongoDB with the following collections:

1. products collection:
   - _id: String (product ID, primary key)
   - product_name: String (required)
   - description: String (optional)
   - location_id: String (optional, references locations._id)

2. locations collection:
   - _id: String (location ID, primary key)
   - location_name: String (required)

3. movements collection:
   - _id: ObjectId (auto-generated by MongoDB)
   - timestamp: DateTime (required)
   - from_location: String (optional, references locations._id)
   - to_location: String (optional, references locations._id)
   - product_id: String (required, references products._id)
   - qty: Integer (required)

Note: This application uses PyMongo for MongoDB operations.
No ORM models are needed as MongoDB is a document database.
"""
